### ISSUE TITLE
Bug: トレイラー動画が再生されない

### ISSUE THREAD

**Issue by A-yum3** [gunners6518/Netflix-clone#49]
## 問題

- クリック時にトレイラー動画が再生されるはずが、行われない
- クリックはできるが、正常に動作が行われない

### 原因

request.jsに指定されているAPIのエンドポイントは[tvであるため](https://github.com/gunners6518/Netflix-clone/blob/main/src/request.js#L5-L11)、
[この箇所](https://github.com/gunners6518/Netflix-clone/blob/main/src/components/Row.tsx#L61)にてハードコーディングされているURLが`movie`ではなく、`tv`が適切ではないでしょうか？

**Comment by gunners6518** [comment]
ご指摘ありがとうございます。

以下のcommitにてリファクタリングを行った際に修正しました。
217b82e143e0e372ad6a757ca24f26718e0c6f7f
